fix '3.1.0' was not found
jakeswenson/BitBetter pull request #116
Opened 2021-08-28 10:09 UTC by clanto007

I tried to fix the problem updating the used SDK to 5.0

2021-08-28 10:13 UTC, captainhook commented
Looks good to me; I will add a few others to reviews before it's merged.

Thank you very much.

2021-08-29 03:32 UTC, anhyzer5525 reviewed
After making all of these changes to my instance and then running the update I was successfully able to upgrade and add new passwords into my vault.

Good job on fixing this!

2021-08-30 07:32 UTC, h44z requested changes
I think it would be better to fix the new dotnet SDK version to 5.0 as we are referencing this explicit version in some files.

2021-08-30 07:32 UTC, h44z commented on src/licenseGen/Dockerfile
> +FROM mcr.microsoft.com/dotnet/sdk as build
can we fix the version to :5.0 if we are using netcoreapp5.0 below?

```suggestion
FROM mcr.microsoft.com/dotnet/sdk as build:5.0
```

2021-08-30 07:32 UTC, h44z commented on build.sh
> +docker run --rm -v "$DIR/src/bitBetter:/bitBetter" -w=/bitBetter mcr.microsoft.com/dotnet/sdk sh build.sh
can we fix the version to :5.0 if we are using netcoreapp5.0 in the other files?

```suggestion
docker run --rm -v "$DIR/src/bitBetter:/bitBetter" -w=/bitBetter mcr.microsoft.com/dotnet/sdk:5.0 sh build.sh

2021-08-30 14:06 UTC, clanto007 commented
@h44z thank you

2021-08-31 08:04 UTC, h44z commented on src/licenseGen/Dockerfile
> +FROM mcr.microsoft.com/dotnet/sdk as build:5.0
```suggestion
FROM mcr.microsoft.com/dotnet/sdk:5.0 as build
```

2021-08-31 08:05 UTC, h44z approved these changes

2021-08-31 08:18 UTC, merged